import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";
import About from "./components/about";
import Projects from "./components/projects";
import Contact from "./components/contact";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <Header />
        <main className="flex-grow">
        <About />
        <Projects />
        <Contact />
        {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
